# Generated by Django 5.2.11 on 2026-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rfid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='rfid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
