# Generated by Django 5.2.11 on 2026-03-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupay_app', '0002_transaction_rfid_wallet_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='created_by',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
