# Generated by Django 5.2.11 on 2026-03-14 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupay_app', '0004_parent_created_at_student_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bankAccount',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='ifsc',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Laundry', 'Laundry'), ('Printing', 'Printing'), ('Canteen', 'Canteen')], default='Stationary', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
