# Generated by Django 5.2.11 on 2026-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupay_app', '0005_remove_vendor_address_remove_vendor_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('stationary', 'Stationary'), ('canteen', 'Canteen'), ('laundry', 'Laundry'), ('printing', 'Printing')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Admin', max_length=50)),
            ],
        ),
    ]
