# Generated by Django 5.2.11 on 2026-03-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupay_app', '0006_vendorlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorlogin',
            old_name='created_at',
            new_name='login_time',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='ownerName',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='vendorName',
        ),
        migrations.AddField(
            model_name='vendorlogin',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edupay_app.vendor'),
        ),
    ]
